export LC_ALL=en_GB.UTF-8
export LANG=en_GB.UTF-8
export LANGUAGE=en_GB.UTF-8

# Ensure that we don't source again, if running under tmux
#(( SOURCED_PROFILE )) && return
#export SOURCED_PROFILE=1

if [[ -r "${HOME}/.bashrc" ]]; then
	source "${HOME}/.bashrc"
fi

export PATH="$HOME/.cargo/bin:$PATH"
