# ~/.bashrc: executed by bash(1) for non-login shells.

export PS1="[LOCAL] \w $ "
export CLICOLOR=1

export PATH="/usr/local/sbin:$PATH"

export GOPATH="$HOME/Projects/go"
export PATH="$PATH:$GOPATH/bin"


OS=$(uname)
if [[ "$OS" == "Linux" ]]; then
  alias l='ls -CF'
  alias la='ls -A'
  alias ll='ls -alF'
  alias ls='ls --color=auto'
elif [[ "$OS" == "Darwin"* ]]; then
  # Brew is slow, so calculate the prefix once
  export BREW_PREFIX="/usr/local/opt"
  export HOMEBREW_AUTO_UPDATE_SECS="604800" # Update once a week max.
  export PATH="$(brew --prefix qt@5.5)/bin:$PATH"
fi

shopt -s checkwinsize

umask 022

# Aliases
alias ll='ls -lhA'
alias mkdir='mkdir -p -v'
alias recent="ls -lAt | head"
alias rg='rg --hidden'
alias git-prunebranches='[ "$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)" == "master" ] && git branch --merged master | grep -v "\* master" | xargs -n 1 git branch -d'
alias pg11="docker run --rm  --name postgres-11.2 -e POSTGRES_PASSWORD=docker -d -p 5432:5432 -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data  postgres:11.2"
alias pg94="docker run --rm  --name postgres-9.4 -e POSTGRES_PASSWORD=docker -d -p 5431:5432 -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data  postgres:9.4"
alias k='kubectl'

# Bash history commands
export HISTSIZE=10000 # Keep 10000 lines in session history
export HISTFILESIZE=100000 # Truncate file at 100,000 lines
# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups,ignorespace
export HISTIGNORE="&:ls:ll:la:l:pwd:exit:clear:gs"
# Don't overwrite history if using multiple bash sessions
shopt -s histappend

# Don't immediately execute command when using history substitution
shopt -s histverify

# Bash eternal history:
# http://www.debian-administration.org/articles/543
#[[ ! -f $HOME/.bash_eternal_history ]] && (touch $HOME/.bash_eternal_history; chmod 0600 $HOME/.bash_eternal_history)
#export HISTTIMEFORMAT="%s "
# Append, because z.sh may have already tampered with PROMPT_COMMAND
#PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND }"'echo $$ $USER "$(history 1)" >> ~/.bash_eternal_history'


#[ -s "$HOME/.autoenv/activate.sh" ] && source "$HOME/.autoenv/activate.sh"
#[ -f "${BREW_PREFIX}/autoenv/activate.sh"  ] && source "${BREW_PREFIX}/autoenv/activate.sh"
#[ -s "$HOME/src/liquidprompt/liquidprompt" ] && source "$HOME/src/liquidprompt/liquidprompt"

# TODO is there any practical difference between my version (top) and the vendored version (bottom)?
# [ -f "$HOME/.fzf.bash" ] && source "$HOME/.fzf.bash"
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
# omit --follow, because otherwise it spews errors about broken symlinks all
# over the place (e.g. pruned go dependencies)
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --glob "!.git/*"'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='--height 100%'
# why is no-reverse required??
export FZF_CTRL_T_OPTS='--height 100% --no-reverse --bind ctrl-j:down,ctrl-k:up'

[ -x "$(command -v rbenv)" ] && eval "$(rbenv init -)"
alias be='bundle exec'
alias c="pbcopy"
alias shac="git rev-parse HEAD | tr -d '\\n' | pbcopy"

gh() {
	if git remote > /dev/null; then
		URL=$(git remote -v | head -n1 | awk '/fetch/{print $2}' | sed -Ee 's#(git@|git://)#http://#' -e 's@com:@com/@')
		echo open "$URL"
	fi
}

diffocop() {
	(
		cd "$(git rev-parse --show-toplevel)" && \
			git diff master --name-only --diff-filter=ACMRTUXB \
			| grep '\.rb$' \
			| tr '\n' ' ' \
			| xargs bundle exec rubocop
	)
}

for filename in ~/.bashrc.private*; do
	# This is to ensure we don't break if there's nothing that matches the glob
	[ -e "$filename" ] || continue
	source "$filename"
done

export PS1="[LOCAL] \w $ "

export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --glob "!.git/*"'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='--height 100%'
export FZF_CTRL_T_OPTS='--height 100% --no-reverse --bind ctrl-j:down,ctrl-k:up'

# Git setup
alias g=git
alias gp='git push'
alias gpf='git push -f'
alias gpl='git pull'
alias gcob='git checkout -b'
# scmpuff for sane git workflow
# Other aliases included in it:
#alias gs='scmpuff_status'
#alias ga='git add'
#alias gd='git diff'
#alias gl='git log'
#alias gco='git checkout'
#alias grs='git reset'
eval "$(scmpuff init -s)"

# Everything that shouldn't be on a public repo is here
[ -f ~/.bashrc.private ] && source ~/.bashrc.private

for filename in ~/.bashrc.private*; do
  # This is to ensure we don't break if there's nothing that matches the glob
  [ -e "$filename" ] || continue
  source "$filename"
done

export BASH_COMPLETION_COMPAT_DIR=/usr/local/etc/bash_completion.d
[[ -r /usr/local/etc/profile.d/bash_completion.sh ]] && . /usr/local/etc/profile.d/bash_completion.sh

